fixing hexdec on a 16 char hex number, which could actually exceed INT64
census-ecosystem/opencensus-php-exporter-jaeger pull request #8
Opened 2018-10-03 16:17 UTC by dragoscirjan

On a 16 'digits' hex chunck, i.e. `bea15bfc5e308b1a`, `hexdec` method can trigger erros, because the converted number could exceed PHP integer side. 

A solution would be to create a _hexdec method using [php-bc](http://php.net/manual/en/book.bc.php) or [php-gpm](http://php.net/manual/en/book.gmp.php) to convert the chunk to a decimal number, then convert the number to a 64 bit signed INT number and parse it with `intval`.

This is my approach, it's not the best, so hoping you guys will refine it further :)

2018-10-05 09:17 UTC, dragoscirjan commented
Need to fix some things before getting back with this PR.

2018-10-05 14:47 UTC, chingor13 requested changes
Thanks for submitting this!

2018-10-05 14:47 UTC, chingor13 commented on src/Jaeger/SpanConverter.php
> +        if (self::$preferredBigMathExt === self::BIG_MATH_BC) {
Can we turn this into an interface with 2 separate implementations and let us not have to do this check every time? We can also potentially detect the default implementation based on which extensions are loaded.

2018-10-05 14:47 UTC, chingor13 commented on src/Installer.php
> +        if (!function_exists('bcadd') && !function_exists('gmp_add')) {
Let's use `extension_loaded` here - a user *could* have `bcadd` or `gmp_add` implemented somewhere in the function lookup chain and not the rest.

2018-10-08 11:56 UTC, dragoscirjan commented
Hi @chingor13, 
Please see code changes for the suggestions you have made. I think this is the best form this could be done, for now.

2018-10-08 18:30 UTC, chingor13 reviewed
Thank you! The refactoring looks good so far. Just added a few smallish things.

2018-10-08 18:30 UTC, chingor13 commented on src/JaegerExporter.php
> +        $this->spanConverter = empty($options['spanConverter']) ? new SpanConverter() : $options['spanConverter'];
1. Is there a need for the span converter to be injected? It's not being used for tests.

2. This needs an instance variable declaration above.

2018-10-08 18:30 UTC, chingor13 commented on src/Jaeger/SpanConverterInterface.php
> +interface SpanConverterInterface
I don't think this interface is needed. There's only one implementation and its internal (or probably should be) until the need arises for a separate implementation.

2018-10-08 18:30 UTC, chingor13 commented on src/Jaeger/HexdecConverter.php
> +class HexdecConverter implements HexdecConverterInterface
Please add a class description phpdoc.

2018-10-08 18:30 UTC, chingor13 commented on src/Jaeger/HexdecConverterBcMath.php
> +class HexdecConverterBcMath implements HexdecConverterInterface
Please add a class description phpdoc.

2018-10-08 18:30 UTC, chingor13 commented on src/Jaeger/HexdecConverterInterface.php
> +  *
Please fill this out.

2018-10-09 16:43 UTC, chingor13 approved these changes
LGTM. Thanks!

2018-10-09 16:43 UTC, merged

2018-11-23 21:34 UTC, un000 commented
@chingor13 could you make a release on this PR?